chakra-ui/chakra-ui-vue-next

README.md, playground/src/App.vue
=> chore: Styled all anchor tags and fix some typo

_templates/generator/component/component.ts.ejs.t, _templates/generator/component/examples.vue.ejs.t, _templates/generator/component/index.ts.ejs.t, docs/.vitepress/config.js, docs/components/badge.md, package.json, packages/c-badge/README.md, packages/c-badge/examples/base-badge.vue, packages/c-badge/examples/outline-badges.vue, packages/c-badge/examples/solid-badge.vue, packages/c-badge/examples/subtle-badges.vue, packages/c-badge/package.json, packages/c-badge/src/badge.ts, packages/c-badge/src/index.ts, packages/c-badge/tests/__snapshots__/c-badge.test.ts.snap, packages/c-badge/tests/c-badge.test.ts, packages/c-badge/tsconfig.json, packages/c-button/src/button.utils.ts, packages/core/src/index.ts, packages/utils/src/object.ts, playground/src/main.ts
- Adds badge component
- Adds badge examples
- Adds badge docs template
- [n] No
=> feat: badge component 

_templates/generator/component/component.ts.ejs.t, _templates/generator/component/examples.vue.ejs.t, _templates/generator/component/index.ts.ejs.t, docs/.vitepress/config.js, docs/components/badge.md, package.json, packages/c-badge/README.md, packages/c-badge/examples/base-badge.vue, packages/c-badge/examples/outline-badges.vue, packages/c-badge/examples/solid-badge.vue, packages/c-badge/examples/subtle-badges.vue, packages/c-badge/package.json, packages/c-badge/src/badge.ts, packages/c-badge/src/index.ts, packages/c-badge/tests/__snapshots__/c-badge.test.ts.snap, packages/c-badge/tests/c-badge.test.ts, packages/c-badge/tsconfig.json, packages/c-button/src/button.utils.ts, packages/core/src/index.ts, packages/utils/src/object.ts, playground/src/main.ts
Aggregates teh following PRs:
- #22
=> feat: add badge to core

_templates/generator/component/index.ts.ejs.t, _templates/generator/component/package.json.ejs.t, _templates/generator/module/package.json.ejs.t, package.json, packages/c-alert/package.json, packages/c-badge/package.json, packages/c-button/package.json, packages/c-icon/package.json, packages/c-portal/README.md, packages/c-portal/examples/simple-portal.vue, packages/c-portal/package.json, packages/c-portal/src/index.ts, packages/c-portal/src/portal.ts, packages/c-portal/src/portal.utils.ts, packages/c-portal/tests/__snapshots__/portal.test.ts.snap, packages/c-portal/tests/portal.test.ts, packages/c-portal/tsconfig.json, packages/c-reset/package.json, packages/c-spinner/package.json, packages/c-theme-provider/package.json, packages/c-visually-hidden/package.json, packages/core/package.json, packages/core/src/index.ts, packages/system/package.json, packages/test-utils/package.json, packages/theme/package.json
- Adds the internaly used Portal component
-
-
=> feat/portal: portal component

packages/c-popper/examples/base-vue-popper.vue
Implementation in first commit, comments in the second 😁 
This PR has been discussed with @codebender828 via Discord.
=> refactor(motion): prefer useMotion for Motion transitions

.changeset/empty-dragons-wait.md, .changeset/pre.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/core/src/index.ts
Core was not exporting popper and portal component packages
- chore: releases fix for component exports in core package
=> chore: release fix for component exports in core package

_templates/generator/tooling/README.md.ejs.t, _templates/generator/tooling/package.json.ejs.t, _templates/generator/tooling/src.ts.ejs.t, _templates/generator/tooling/test-file.test.ts.ejs.t, _templates/generator/tooling/tsconfig.json.ejs.t, lerna.json, package.json, tooling/auto-import/README.md, tooling/auto-import/package.json, tooling/auto-import/src/index.ts, tooling/auto-import/tests/vue-auto-import.test.ts, tooling/auto-import/tsconfig.json, vite.config.ts
Currently components aren't auto imported for Chakra UI Vue
- Exports `componentResolver` function to allow components to be auto imported from Vite projects
=> feat: vite components auto import for `@chakra-ui/vue-next`

.changeset/pre.json, .changeset/slimy-bugs-give.md, _templates/generator/tooling/README.md.ejs.t, _templates/generator/tooling/package.json.ejs.t, _templates/generator/tooling/src.ts.ejs.t, _templates/generator/tooling/test-file.test.ts.ejs.t, _templates/generator/tooling/tsconfig.json.ejs.t, lerna.json, package.json, tooling/auto-import/CHANGELOG.md, tooling/auto-import/README.md, tooling/auto-import/package.json, tooling/auto-import/src/index.ts, tooling/auto-import/tests/vue-auto-import.test.ts, tooling/auto-import/tsconfig.json, vite.config.ts
=> chore: release `@chakra-ui/vue-auto-import` component resolver

website/src/components/home/Hero.vue
- Adds gradient background on > md devices
- Adds link to react version of Chakra
=> feat: add gradient background and link to react version of chakra

.changeset/neat-rules-cry.md, packages/system/src/system.utils.ts, website/src/components/SandboxExample.vue, website/src/pages/index.vue
- Add Iframe to Dom Elements list
- Add Code Sandbox example to home page
TODO: Update the Example with a Chakra UI Vue Chidori V1 example instead of Chakra Ui Vue v0
=> Docs: Code Sandbox example on homepage

website/src/components/SandboxExample.vue
The Code Sandbox example was of Chakra UI Vue v0.
- Update the CSB example to Vue 3 and Chakra UI Vue Chidori v1
- Add title and description text
Should we take a look at the Title and description text? Or is it OK that they are the same as on the Chakra UI React website?
=> feat: update example with vue 3 and chakra v1 and add content text

.changeset/proud-apples-compare.md, .changeset/yellow-weeks-kick.md, packages/c-flex/examples/base-flex.vue, packages/c-flex/src/flex.ts
It wasn't possible to use the object notation for adding responsive styles 
- Change ArrayOrStringProp to SystemStyleObject
=> fix(component): fix c-flex prop to be also object

CONTRIBUTING.md
=> docs(contributing): add step yarn build

.changeset/metal-tables-poke.md, packages/core/src/helpers/css-reset.ts
Some console.logs were printed in the console. 
- Removed the console.logs
-
-
=> fix: console logs in css reset

.changeset/bright-geese-tickle.md, packages/system/src/chakra.ts, yarn.lock
Adds form control and input changeset
=> chore: create form control and input chanegset

docs/.vitepress/config.js, docs/pages/features/chakra-factory.md, docs/pages/features/color-mode.md, docs/pages/features/css-variables.md, docs/pages/features/gradient.md, docs/pages/features/responsive-styles.md, docs/pages/features/text-and-layer-styles.md, docs/pages/getting-started/principles.md
- Add docs under feature topic
=> Docs: features

packages/c-accordion/tests/c-accordion.cy.tsx
Signed-off-by: Shyrro <zsahmane@gmail.com>
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been reviewed and added / updated if needed (for bug fixes
Currently, Cypress tests freeze on "Your tests are loading" on every component. That is because of a wrong import in accordion tests.
Cypress tests run normally
This is important because it means that cypress tests were not reliable
=> fix(tests): fix accordion import

packages/c-avatar/README.md, packages/c-avatar/examples/badge-c-avatar.vue, packages/c-avatar/examples/base-c-avatar.vue, packages/c-avatar/examples/c-group-avatar.vue, packages/c-avatar/examples/index.ts, packages/c-avatar/index.tsx, packages/c-avatar/package.json, packages/c-avatar/src/c-avatar-badge.tsx, packages/c-avatar/src/c-avatar-group.tsx, packages/c-avatar/src/c-avatar.tsx, packages/c-avatar/src/index.tsx, packages/c-avatar/src/utils.ts, packages/c-avatar/tests/__snapshots__/c-avatar-badge.test.ts.snap, packages/c-avatar/tests/__snapshots__/c-avatar-group.test.ts.snap, packages/c-avatar/tests/__snapshots__/c-avatar.test.ts.snap, packages/c-avatar/tests/c-avatar-badge.test.ts, packages/c-avatar/tests/c-avatar-group.test.ts, packages/c-avatar/tests/c-avatar.cy.tsx, packages/c-avatar/tests/c-avatar.test.ts, packages/c-avatar/tsconfig.json, packages/core/package.json, packages/core/src/index.ts, packages/layout/src/box.tsx, packages/layout/src/wrap.ts, packages/layout/tests/__snapshots__/layout.test.ts.snap, packages/theme/src/components/avatar.ts
Signed-off-by: Shyrro <zsahmane@gmail.com>
This PR introduces the CAvatar component alongs with the CAvatarBadge and CAvatarGroup.
=> feat: add avatar component

CONTRIBUTING.md
Updates the `CONTRIBUTING.md` file, hoping to provide more accurate details in running the project locally, specifically in terms of initial setup, running the playground server, and address any issues that may arise if the contributor is a Windows OS user.
Fixes: #168 
N/A
=> docs(contributing): update details

components.d.ts, packages/c-pin-input/README.md, packages/c-pin-input/examples/base-c-pin-input.vue, packages/c-pin-input/examples/index.ts, packages/c-pin-input/examples/with-clear-button.vue, packages/c-pin-input/examples/with-events.vue, packages/c-pin-input/index.ts, packages/c-pin-input/package.json, packages/c-pin-input/src/c-pin-input.tsx, packages/c-pin-input/src/index.ts, packages/c-pin-input/src/use-pin-input.ts, packages/c-pin-input/tests/__snapshots__/c-pin-input.test.ts.snap, packages/c-pin-input/tests/c-pin-input.cy.tsx, packages/c-pin-input/tests/c-pin-input.test.ts, packages/c-pin-input/tsconfig.json, packages/core/package.json, packages/core/src/index.ts, packages/system/src/providers.ts, packages/theme/src/components/pin-input.ts, yarn.lock
Signed-off-by: Shyrro <zsahmane@gmail.com>
None
Pin Input available
- Due to `zag-js`, some behavior is not testable in `jest`/`cypress`. This is due to the fact that `zag` prevents some default behavior of the input fields to handle some events, which does not get along well with testing tools. 
This is kind of fine though, because the behavior is already tested on Zag's side so we won't have to worry too much about it.
- On another note, this uses the version `0.1.14` of `@zag-js/pin-input` instead of the latest version. This is because the latest release at this date, is `esm` only. Version should be upgraded when zag supports `cjs` again.
=> feat(cpininput): add c pin input

_templates/generator/component/tsup.config.ts.ejs.t, packages/c-menu/README.md, packages/c-menu/examples/base-menu.vue, packages/c-menu/examples/controlled-menu.vue, packages/c-menu/examples/index.ts, packages/c-menu/examples/infinite-nested-menu.vue, packages/c-menu/examples/menu-groups.vue, packages/c-menu/index.tsx, packages/c-menu/package.json, packages/c-menu/src/c-menu-list.tsx, packages/c-menu/src/c-menu.tsx, packages/c-menu/src/composables.ts, packages/c-menu/src/index.tsx, packages/c-menu/src/nested-menu.tsx, packages/c-menu/tests/__snapshots__/chakra-ui-c-menu.test.ts.snap, packages/c-menu/tests/c-menu.cy.tsx, packages/c-menu/tests/chakra-ui-c-menu.test.ts, packages/c-menu/tsconfig.json, packages/c-menu/tsup.config.ts, packages/core/package.json, packages/core/src/components.ts, packages/utils/src/match.ts, pnpm-lock.yaml
Signed-off-by: Shyrro <zsahmane@gmail.com>
-
-
-
=> feat(menu): add cmenu

packages/c-form-control/examples/components.tsx, packages/c-form-control/tests/c-form-control.cy.tsx, packages/c-form-control/tsconfig.json, packages/c-input/package.json, packages/vue/src/index.ts
=> feat(exports): explicit exports from vue next

.changeset/spicy-doors-heal.md, @types/components.d.ts, _templates/generator/component/package.json.ejs.t, _templates/generator/module/package.json.ejs.t, _templates/generator/tooling/package.json.ejs.t, components.d.ts, packages/c-live-region/README.md, packages/c-live-region/examples/simple-live-region.vue, packages/c-live-region/index.tsx, packages/c-live-region/package.json, packages/c-live-region/src/index.ts, packages/c-live-region/src/live-region.ts, packages/c-live-region/src/use-live-region.ts, packages/c-live-region/tests/__snapshots__/c-live-region.test.ts.snap, packages/c-live-region/tests/c-live-region.test.ts, packages/c-live-region/tsconfig.json, packages/c-live-region/tsup.config.ts, packages/c-textarea/README.md, packages/c-textarea/examples/simple-textarea.vue, packages/c-textarea/index.tsx, packages/c-textarea/package.json, packages/c-textarea/src/c-textarea.tsx, packages/c-textarea/src/index.tsx, packages/c-textarea/tests/__snapshots__/c-textarea.test.ts.snap, packages/c-textarea/tests/c-textarea.test.ts, packages/c-textarea/tsconfig.json, packages/c-textarea/tsup.config.ts, packages/vue/package.json, packages/vue/src/index.ts, pnpm-lock.yaml
- feat: create live region component
- feat(textarea): create textarea component
- feat: create changeset
Closes #206 
=> feat: `CLiveRegion`, `CTextarea` `useBreakpoint` and `useBreakpointValue` hooks
